version: 2

sources:
  - name: raw_data
    description: "The raw data from the taxi rides in New York"
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
      - name: green_tripdata