version: 2

models:
  - name: dim_vendors
    description: "A dimension table containing information about taxi vendors."
    columns:
      - name: vendorid
        description: "The unique identifier for the taxi vendor."
      - name: vendor_name
        description: "The name of the taxi vendor."
      - name: vendor_address
        description: "The address of the taxi vendor's headquarters."
      - name: vendor_phone
        description: "The phone number for the taxi vendor's customer service."
      - name: created_at
        description: "The timestamp when the record was created."
      - name: updated_at
        description: "The timestamp when the record was last updated."